import type { Metadata } from "next";
import { GameContextProvider } from "@/context/GameContext";
import "./globals.css";

export const metadata: Metadata = {
  title: "Tic Tac Toe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <GameContextProvider>{children}</GameContextProvider>
      </body>
    </html>
  );
}
